apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server-text-encoder
  name: fastapi-server-text-encoder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastapi-server-text-encoder
  type: LoadBalancer
status:
  loadBalancer: {}
