apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-server-diffusion-model
  name: fastapi-server-diffusion-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server-diffusion-model
  strategy: {}
  template:
    metadata:
      labels:
        app: fastapi-server-diffusion-model
    spec:
      containers:
      - image: gcr.io/gcp-ml-172005/sd-fastapi-diffusion-model:latest
        name: fastapi-k8s-diffusion-model
        ports:
        - containerPort: 80
        resources:
          limits:
            nvidia.com/gpu: 1
