apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server-decoder
  name: fastapi-server-decoder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastapi-server-decoder
  type: LoadBalancer
status:
  loadBalancer: {}
