apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tfs-server-text-encoder
  name: tfs-server-text-encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfs-server-text-encoder
  strategy: {}
  template:
    metadata:
      labels:
        app: tfs-server-text-encoder
    spec:
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-sd-text-encoder:latest
        name: tfs-k8s-text-encoder
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi