FROM tensorflow/serving

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install git -y

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install

RUN git clone https://huggingface.co/keras-sd/tfs-text-encoder-base64
RUN rm tfs-text-encoder-base64/README.md

RUN mkdir -p /models/text-encoder-base64/1
RUN cp -r tfs-text-encoder-base64/* /models/text-encoder-base64/1/ 

ENV MODEL_NAME=text-encoder-base64
