FROM tensorflow/serving:nightly-gpu

RUN apt-get update
RUN apt-get install git -y

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install

RUN git clone https://huggingface.co/keras-sd/tfs-decoder-base64
RUN rm tfs-decoder-base64/README.md

RUN mkdir -p /models/decoder-base64/1
RUN cp -r tfs-decoder-base64/* /models/decoder-base64/1/ 

ENV MODEL_NAME=decoder-base64
