FROM tensorflow/serving:nightly-gpu

RUN apt-get update
RUN apt-get install git -y

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install

RUN git clone https://huggingface.co/keras-sd/tfs-diffusion-model-v2-base64
RUN rm tfs-diffusion-model-v2-base64/README.md

RUN mkdir -p /models/diffusion-model-v2-base64/1
RUN cp -r tfs-diffusion-model-v2-base64/* /models/diffusion-model-v2-base64/1/ 

ENV MODEL_NAME=diffusion-model-v2-base64
ENV TF_CPP_VMODULE=http_server=1
