apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tfs-server-text-encoder-base64
  name: tfs-server-text-encoder-base64
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    targetPort: 8501
    name: tf-serving-restapi
  selector:
    app: tfs-server-text-encoder-base64
  type: LoadBalancer
status:
  loadBalancer: {}